### ISSUE TITLE
cx-benchmark fails

### ISSUE THREAD

**Issue by Diablo2050** [skycoin/cx#500]
When i try to run `cx ackermann-function.cx` i get
```
error: ackermann-function.cx:6 function 'bool.not' expected input argument of type 'bool'; 'i32' was provided
error: ackermann-function.cx:9 function 'bool.not' expected input argument of type 'bool'; 'i32' was provided
error: ackermann-function.cx:22 identifier 'time' does not exist
```

**Comment by PratikDhanave** [comment]
@Diablo2050 you need add "import time" after package main

**Comment by PratikDhanave** [comment]
@Diablo2050 for opcode OP_BOOL_NOT we need to convert i32 to bool.

**Comment by SkycoinSynth** [comment]
Fixed.

**Comment by Diablo2050** [comment]
Still not working after pulling on develop branch and trying again i get:

`error: ackermann-function.cx:8 function 'i32.bool' does not exist
panic: runtime error: index out of range [-1]

goroutine 1 [running, locked to thread]:
github.com/skycoin/cx/cxgo/actions.PostfixExpressionFunCall(0x0, 0x0, 0x0, 0xc0001e0040, 0x1, 0x1, 0x0, 0x1, 0x0)
        /home/amr/Documents/misc/golang/cx/cxgo/actions/postfix.go:156 +0x26a
github.com/skycoin/cx/cxgo/parser.yyParse(0xac6488, 0xc00054e090, 0xc00054e090)
        /home/amr/Documents/misc/golang/cx/cxgo/parser/cxgo.go:2222 +0x7445
github.com/skycoin/cx/cxgo/parser.Parse(...)
        /home/amr/Documents/misc/golang/cx/cxgo/parser/cxgo.go:18
github.com/skycoin/cx/cxgo/cxgo.ParseSourceCode(0xc0001e0498, 0x1, 0x1, 0xc0001c2e40, 0x1, 0x1)
        /home/amr/Documents/misc/golang/cx/cxgo/cxgo/cxgo.go:78 +0x40f
main.parseProgram(0x0, 0xab7c88, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /home/amr/Documents/misc/golang/cx/cmd/cx/main.go:163 +0x348
main.Run(0xc0000cc010, 0x1, 0x1)
        /home/amr/Documents/misc/golang/cx/cmd/cx/main.go:91 +0x368
main.main()
        /home/amr/Documents/misc/golang/cx/cmd/cx/main.go:24 +0x66`

**Comment by Diablo2050** [comment]
@SkycoinSynth
